### PR TITLE
Python3 Compatibility

### PR DESCRIPTION
**Pull request by jarondl**
The only required modification was converting
the relative import to an absolute import. Now it should
work for both Python2 and Python3

### CODE REVIEW

**Comment by jarondl** [comment]
@sarathsp06 any chance to merge this and bump versions? This would help our effort at yelp/elastalert#1178

**Comment by AndreLouisCaron** [comment]
I'm confused about the Python 3 compatibility because `.travis.yml` targets multiple Python 3 versions.

In the meantime, the Travic-CI build is failing.  The logs suggest that `pytest` is missing and it doesn't seem to be in the `requirements.txt` file.

**Comment by AndreLouisCaron** [comment]
OK, after a closer look it seems this project does not have any tests at all...  I'm not sure why there is a `.travis.yml` file.

**Comment by sarathsp06** [comment]
@jarondl merged @AndreLouisCaron 's pull request .

**Pull request closed without merging**
