### PR TITLE
Adds test suite and Python 3.5 compatibility

### PR DESCRIPTION
**Pull request by AndreLouisCaron**
This will make `.travis.yml` useful and help close Yelp/elastalert#1178.

### CODE REVIEW

**Comment by sarathsp06** [comment]
I was not active on this account for sometime thanks

**Comment by AndreLouisCaron** [comment]
Thanks for the quick merge!  Any chance you can release this to PyPI?

**Comment by sarathsp06** [comment]
It is relaesed to PyPI as 0.1.5

**Comment by AndreLouisCaron** [comment]
Nice, thanks a bunch!

**Comment by sarathsp06** [comment]
@AndreLouisCaron  Thank you for the mock test cases , the whole library was a half hour hack for a hackathon . Did not bother adding test cases

**Comment by jarondl** [comment]
Wow, nice work @AndreLouisCaron

**Pull request merged**
